name       : perl-filesys-df
version    : 0.92
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/I/IG/IGUTHRIE/Filesys-Df-0.92.tar.gz : fe89cbb427e0e05f1cd97c2dd6d3866ac6b21bc7a85734ede159bdc35479552a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Filesys::Df provides a way to obtain filesystem disk space information.
description: |
    This module provides a way to obtain filesystem disk space information.
builddeps  :
    - perl-extutils-makemaker
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
